export const contactForm = {
    en: {
        formHeader: "Please use this form to get a non-binding quote for your request.",
        company: "Company",
        name: "Name*",
        street: "Street*",
        postalCity: "Postal Code*, City*",
        country: "Country",
        phone: "Phone*",
        email: "Email*",
        description: "Description*",
        sourceLanguage: "Source Language",
        targetLanguage: "Target Language",
        submit: "Submit",
    },
    de: {
        formHeader: "Bitte nutzen Sie dieses Formular, um ein unverbindliches Angebot für Ihre Anfrage zu erhalten.",
        company: "Firma",
        name: "Name*",
        street: "Straße*",
        postalCity: "PLZ*, Ort*",
        country: "Land",
        phone: "Telefon*",
        email: "eMail*",
        description: "Beschreibung*",
        sourceLanguage: "Ausgangssprache",
        targetLanguage: "Zielsprache",
        submit: "Absenden",
    },
    fr: {
        formHeader: "Utilisez ce formulaire pour obtenir un devis non contraignant pour votre demande.",
        company: "Société",
        name: "Nom*",
        street: "Rue*",
        postalCity: "Code Postal*, Ville*",
        country: "Pays",
        phone: "Téléphone*",
        email: "Email*",
        description: "Description*",
        sourceLanguage: "Langue Source",
        targetLanguage: "Langue Cible",
        submit: "Soumettre",
    },
    zh: {
        formHeader: "请使用此表单获取您请求的非绑定报价。",
        company: "公司",
        name: "姓名*",
        street: "街道*",
        postalCity: "邮政编码*, 城市*",
        country: "国家",
        phone: "电话*",
        email: "电子邮件*",
        description: "描述*",
        sourceLanguage: "源语言",
        targetLanguage: "目标语言",
        submit: "提交",
    },
};
